<!DOCTYPE html>
<html lang="en">
<head>
    <base href="/">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    
    <link rel="stylesheet" href="css/home.css">
    
    <script
			src="https://code.jquery.com/jquery-3.7.1.min.js"
			integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo="
			crossorigin="anonymous">
    </script>
</head>
<body>
    <header>
        <img src="images/logo.png" alt="logo" class="logo" width="50px">
        <nav class="navbar">
            <ul>
                <li><a href="home">Home</a></li>
                <li><a href="kanji">Kanji</a></li>
                <li><a href="materials">Quiz</a></li>
                <li><a href="login">Account</a></li>
            </ul>
        </nav>
    </header>
    <main>
    <?php $this->controller->renderView();?>
    </main>
        
</body>
</html>