<form action="" method="post">
    <div class="form-container">
        <h1 class="login-title">Registrate</h1>


        <div class="form-group">
            <input type="email" name="email" placeholder="email">
        </div>

        <div class="form-group">
            <input type="text" name="username" placeholder="username">
        </div>

        <div class="form-group">
            <input type="password" name="password" id="password" placeholder="password">
        </div>
        <button type="submit" id="login_button">submit</button>
    </div>
</form>