<div class="randKanjiContainer">
</div>
<div class="window">
  Choose whitch kanji from different grades you want to add:
  <div>
    <input type="checkbox" class="checkbox" id="grade-1" name="grade-1" />
    <label for="grade-1">Grade 1</label>
  </div>
  
  <div>
    <input type="checkbox" class="checkbox" id="grade-2" name="grade-2" />
    <label for="grade-2">Grade 2</label>
  </div>

  <div>
    <input type="checkbox" class="checkbox" id="grade-3" name="grade-3" />
    <label for="grade-3">Grade 3</label>
  </div>

  <div>
    <input type="checkbox" class="checkbox" id="grade-4" name="grade-4" />
    <label for="grade-4">Grade 4</label>
  </div>

  <div>
    <input type="checkbox" class="checkbox" id="grade-5" name="grade-5" />
    <label for="grade-5">Grade 5</label>
  </div>

  <button id="startQuiz">Start quiz</button>
</div>
<script src="js/config.js"></script>
<script src="js/readyQuiz.js"></script>


